### ISSUE TITLE
Can't go to parent directory when remote directory is set in connection preference.

### ISSUE THREAD

**Issue by shivanandsharma** [Equals182/eqFTP#147] opened 2015-06-20 11:20 UTC
Ideally I'd like to work inside /var/www/html/somesite/wp-content/. But occasionally I'd like to go to the parent folder and I don't see ".." when the remote directory is set to /var/www/html/somesite/wp-content/ in the connection setting.

**Comment by Equals182** [comment] 2015-06-20 11:30
That's because it doesn't work like that. eqFTP uses file-tree representation instead of per-folder. Some crazy guys combine those two, but it's not that easy to do so. So, you can just set remote path to parent folder and work inside `wp-content`. Yes, it will be children folder, one more click, but it should work.

I also would like to point out that, for example, Cyberduck, that uses combined view just goes to unstoppable loop when you go "too far" up the tree, where you are not allowed to go.

So it's not a bug, this is how it's supposed to work. For now there's no `..`, symlinks and other non-ftp cool features. And I think making it work like Cryberduck or any other ftp client that uses combined view will just ruin simplicity.

**Comment by shivanandsharma** [comment] 2015-06-20 11:39
I'm on the Mac. And for the web developer on a Mac, Adobe Brackets is the best code editor. And eqFTP the best s/ftp client. I see a lot of promise in eqFTP to help coders have an alternative to the only paid monopoly of "that one" code editor.

I'm sure (someday) you'll favor full s/ftp client functionality over simplicity at the cost of missing features (think Notepad++). Good work so far! :)

**Comment by Equals182** [comment] 2017-01-10 23:23
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊

**Closed by Equals182** 2017-01-10 23:23 UTC
Labels: feature request
