### ISSUE TITLE
Can't list FTP directories anymore

### ISSUE THREAD

**Issue by phrench** [Equals182/eqFTP#244] opened 2016-11-19 18:21 UTC
I'm running Brackets Release 1.8 build 1.8.0-17108 with the latest eqFTP 0.7.3.

eqFTP won't list the directories of my FTP server connections. The SFTP servers work fine though.

It states that it connected to the FTP server, but then it just keeps spinning the wheel here:
![Image of wheel](http://i.imgur.com/ZKuZ5CT.png)

I've tried both folder retrieving methods in the settings.
And two different FTP servers.

Any ideas?

**Comment by Equals182** [comment] 2016-11-19 18:22
Please check out this issue here: #242

**Comment by phrench** [comment] 2016-11-19 18:24
Fastest tickets reply ever.

The latest version 0.7.3 with the fix is already installed, because without it SFTP wasn't working.

**Comment by Equals182** [comment] 2016-11-19 18:28
oh sorry, didn't see it. 

Can you please add debug log here?
To do so, follow these steps:
* Restart Brackets and turn on Debug in main eqFTP settings
* Press F12 to open DevTools for Brackets and open Console tab
* Wait for error to appear
* Copy-paste console output (**but don't forget to hide sensitive information**)

**Comment by phrench** [comment] 2016-11-19 18:38
Please find the log here: [http://pastebin.com/9QdzahCi](url)

**Comment by Equals182** [comment] 2016-11-20 12:53
Unfortunately the issue is deeper than I thought. I was able to recreate it but no obvious solution found so far. For now I can only suggest downgrading to Brackets 1.7 and eqFTP 0.7.2 if this extension is really necessary. Sorry about that

**Comment by phrench** [comment] 2016-11-20 16:02
Ok. Thank you very much for looking into this!

Will you update this issue once it's fixed?

**Comment by phrench** [comment] 2016-11-20 16:40
Can you make eqFTP 0.7.2 available please? Thanks

**Comment by Equals182** [comment] 2016-11-20 16:42
Try this one: https://github.com/Equals182/eqFTP/blob/master/eqFTP-0.7.2.zip?raw=true
This one should be a version without major changes for Brackets 1.8. Please tell me if it's working for you.

**Comment by Equals182** [comment] 2016-11-20 16:43
As for fix - I'm currently more working on next version of this plugin that doesn't have this issue rn, but I'm really not sure when it will be done, a lot of work ahead and not so much spare time unfortunately.

**Comment by phrench** [comment] 2016-11-21 01:15
Thanks for the link to v0.7.2, it's working with Brackets 1.7. Please update/close this issue once you have the next version ready, so I get notified about it. Your plugin and help is much appreciated!

**Comment by Equals182** [comment] 2017-01-10 23:38
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊

**Closed by Equals182** 2017-01-10 23:38 UTC
