### ISSUE TITLE
Hourglass in logo 

### ISSUE THREAD

**Issue by DPCreations** [Equals182/eqFTP#121] opened 2015-04-13 17:29 UTC
When I open Brackets, inside the eqFTP logo there is an hourglass, which prevent me from opening the extension, and make the queue in the bottom red, as seen in the image below. 
![disbug](https://cloud.githubusercontent.com/assets/5912622/7121228/5a235f60-e213-11e4-9f8c-60ab52633873.png)

EDIT: and yeah, I'm kinda guessing this is built in, but it kinda just is there, no messages or anything.

**Comment by Equals182** [comment] 2015-04-13 20:17
Hmm.. something prevents eqFTP from loading up.

Can you please update from here: `https://github.com/Equals182/Buggy-eqFTP` ([here's how](http://equals182.github.io/eqFTP/#installing) - check beta version installation).

If problem persists - please, follow steps 2 - 5 from [this guide](http://equals182.github.io/eqFTP/#creating-issue)

**Comment by f34rl3ss** [comment] 2015-06-22 10:29
I have the same issue.
Most of the time when i start brackets eqFTP has the hourglass symbol and cannot be openend (even after a minute).
I have to close/reopen brackets a few times then until it works.
Only plugin running besides eqFTP is "Extract for Brackets (Preview)".
Will test the proposed solution when i have the time.

**Comment by Equals182** [comment] 2015-06-22 11:05
There's no solution yet, I just need some debug info to understand the issue. I have same thing sometimes but not that often. It takes me 1 reload to resolve it. And I'm not sure if it's extension's problem or Brackets/Node.

**Comment by f34rl3ss** [comment] 2015-06-22 11:19
This is rather funny.
Had this issue like 5 out of 6 times when opening brackets.
Now turned on debug mode to get you some debug info, and now the problem is gone (for now?).
Restartet brackets 20 times now and no problems with eqFTP not loading.
Even after turning debug mode off again.
Will let debug mode stay on for some time and see if it is reproducible.

**Comment by Equals182** [comment] 2017-01-10 23:22
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊

**Closed by Equals182** 2017-01-10 23:22 UTC
