### ISSUE TITLE
Connection is made but no remote files shown or able to upload

### ISSUE THREAD

**Issue by logopogo** [Equals182/eqFTP#201] opened 2016-02-08 06:03 UTC
Hi.
Everything looks to be connecting ok (I get the green notification box saying 'connected') but I can't see the remote server files and any queued files just sit there with a status of 'Waiting...' when I process the queue.

I can connect ok to another server.

Brackets version:
Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) 
build timestamp: Tue Jan 12 2016 05:35:00 GMT-0800

eqFTP version:
0.7.2

Debug console attached.

Hoping you can help and thank you in advanced.

**Comment by Equals182** [comment] 2016-02-08 08:29
Hi!
Thanks for feedback. I need your help to debug it.
I just did some changes to see where the issue is. Please update from `https://github.com/Equals182/Buggy-eqFTP` (check [this link](http://equals182.github.io/eqFTP/#installing) to see how to install it) and send me logs after. Lets deal with folder retrieving stuff first.

**Comment by logopogo** [comment] 2016-02-08 10:21
Thanks for looking at this.
I've installed from the URL and attached is the console log.
I tried connecting and editing a file - still no server files showing and this time the modified file wasn't being added to the queue and I couldn't attempt upload at all.
[console 2.txt](https://github.com/Equals182/eqFTP/files/121413/console.2.txt)

**Comment by Equals182** [comment] 2016-02-08 16:38
Please, update from same link again, do same actions and send me new log.
For now I see some weird stuff in PWD response. I've added log line to see
what's wrong with it.

**Comment by logopogo** [comment] 2016-02-08 20:00
Ok, reinstalled and log attached.
[console 3.txt](https://github.com/Equals182/eqFTP/files/122118/console.3.txt)

**Comment by Equals182** [comment] 2016-02-08 22:13
Please change your passwords asap and/or delete/censor logs.
For now I can't say if there are any obvious errors. I'll take a look
tomorrow, in like 9 hours or so.

**Comment by Equals182** [comment] 2016-02-08 22:19
I've changed your comment a bit. Please make sure to change passwords
though, just in case.
Next time I'll send you version with passwords' auto hiding feature to
avoid this stuff.
Thank you for your patience. I'll get back to this issue in 9 hours or so.

**Comment by logopogo** [comment] 2016-02-08 22:51
I've changed passwords. Thanks for letting me know.
PS: the link to the console file is still in your comments as well (in the quoted text). Would be good if these files could be deleted from GitHub completely.

**Comment by Equals182** [comment] 2016-02-09 05:55
I cleaned my comments as well.
To avoid stuff like this, you can email me if you want. It's myslf@ymail.com, I'll answer you from main email right after.

**Comment by Equals182** [comment] 2016-02-09 16:27
I'm really sorry for late response. Please update from same link again and just try to open connection without trying uploading stuff. Then send me just two lines that contains `SEND THIS PLS` and `JUST IN CASE THERES NO USEFUL INFO ABOVE` texts. Nothing more, to prevent leaks of personal data.

**Comment by logopogo** [comment] 2016-02-09 17:20
No problem. Thank you for looking into it.
Line are as follows:
[node-log 4:15:30 AM] SEND THIS PLS [Error: Unable to exec] { text: undefined }
[node-log 4:15:30 AM] JUST IN CASE THERES NO USEFUL INFO ABOVE {} {}

**Comment by Equals182** [comment] 2016-02-09 18:33
I'm not even sure if I can fix it. It's an error from scp2 node module. And honestly I think it's not an error or bug at all - looks like your server have some restrictions. Of course I could try to avoid using `pwd` command, but I think it's pretty much the only way to know what folder the user is in right now. Moreover I'm not sure if it's the only problem - your server could deny any other commands.
I'm sorry to say, but I'm afraid I can't help you with that. At least for now. May be in next version I will try to add more flexibility for any server settings.

**Comment by logopogo** [comment] 2016-02-09 19:29
That's a shame. Was really looking forward to using your plugin with Brackets.
I understand it would be difficult to support every server and their intricacies. Thank you so much for trying though.
If you ever want to run your own tests with my particular server setup (for future development), I can give you access to an account if you like. Happy to help were I can.

**Comment by Equals182** [comment] 2017-01-10 23:29
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊

**Closed by Equals182** 2017-01-10 23:29 UTC
