### ISSUE TITLE
Adding more notifications.

### ISSUE THREAD

**Issue by Miodec** [Equals182/eqFTP#158] opened 2015-07-13 18:32 UTC
Hey!
Ive enabled notifications in the settings and i can only see 'connected' and 'disconnected' notifications. A notification saying **_filename.extension upload completed**_ or **_filename.extension upload failed**_ would be great to have the queue closed and see more of the code, because the little icon on the right is not as much visible as a bright, colorful notification. Is that a planned feature or am i experiencing a little bug?

Thanks

**Comment by Equals182** [comment] 2015-07-13 18:38
This is not a bug and not a planned feature. I just thought adding this notification would be a little bit too much. May be I was wrong. I'll add this soon then.

**Comment by Miodec** [comment] 2015-07-13 18:39
Maybe add a checkbox for the users that would use this feature. If someone doesn't that - he can just uncheck it.

**Comment by Equals182** [comment] 2017-01-10 23:25
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊

**Closed by Equals182** 2017-01-10 23:25 UTC
