### ISSUE TITLE
Downloading Directory doesn't work

### ISSUE THREAD

**Issue by ghost** [Equals182/eqFTP#189] opened 2015-12-07 13:12 UTC
When I right click (secondary click) on a directory and click "download" nothing happens. It would be a really nice feature to download the entire directory if it worked.

![image](https://cloud.githubusercontent.com/assets/9147409/11627634/2b4aed4a-9cba-11e5-998d-5f208e3e17e3.png)

**Comment by Equals182** [comment] 2015-12-07 13:18
It should work, actually. Try to update to 0.7.0 version and check again.
But for real, I do not recommend to use this feature because it's slow and
not really stable.

**Comment by addcms** [comment] 2015-12-07 18:41
I will only be using it for a small folder containing only a few files so it should be pretty quick.
I upgraded to 0.7.0 as you suggested but now it wont connect to the database, I only get a giant spinning gear.

**Comment by Equals182** [comment] 2015-12-07 18:45
Hmm. Can you please give me some debug info? Follow these steps: http://equals182.github.io/eqFTP/#creating-issue

**Comment by addcms** [comment] 2015-12-07 19:13
I have confirmed using another FTP Client (FileZilla) that the FTP Server is up and running.
My Brackets version is:

     Release 1.5 build 1.5.0-16538 (release cf9cf4698) 
     build timestamp: Mon Oct 12 2015 13:14:22 GMT+0100

![image](https://cloud.githubusercontent.com/assets/9147409/11636918/8f53be2a-9cec-11e5-8369-61f4615a73e6.png)

My debug log reads:

    [eqFTP] Loaded (v0.7.0)
    main.js:1595 14:6:25.982 Adding to queue Object {type: "folder", connectionID: 0, path: "", id: "f_1449515185982992", state: "opened"…}callback: undefinedconnectionID: 0id: "f_1449515185982992"path: ""state: "opened"type: "folder"__proto__: Object

![image](https://cloud.githubusercontent.com/assets/9147409/11636899/7a0fff38-9cec-11e5-83c2-132e78c8364f.png)


There are no other errors or anything else happening but it does not connect. I also downgraded and checked and version 0.6.3 does connect just fine.

**Comment by Equals182** [comment] 2015-12-07 19:28
It's definetely not your server's problem. It should work though, I'm using this version every day. Did you restart Brackets manually after update? Restarting via blue button is not enough usually.

**Comment by addcms** [comment] 2015-12-07 19:38
Yes I restarted by going to "Debug > Reload with Extensions"...
I will try quitting it and restarting it all together.

**Comment by addcms** [comment] 2015-12-07 20:30
A full restart also didn't work but at least now I am getting an error. I got a "connection refused" error. But when I check the FTP server log it doesn't even show an attempted login.
I tried it with the IP address of the server instead of the domain name and it worked.
But again on FileZilla the domain name works fine.
Maybe the service you are using to resolve domain names is not working properly?

**Comment by Equals182** [comment] 2015-12-07 20:36
Not sure what's wrong. Maybe it really is some troubles with domain names instead of IPs. I'm not using any services for that, but I may miss some kind of bug in extension. Can you download folders now?

**Comment by addcms** [comment] 2015-12-07 20:40
No actually I can connect and see all the folders/files but now I cant download anything.

**Comment by Equals182** [comment] 2015-12-07 20:42
What does console say?

**Comment by addcms** [comment] 2015-12-07 20:42
Nevermind I closed brackets and restarted it and it works now. But im still connected via IP and not domain

**Comment by Equals182** [comment] 2015-12-07 20:46
Yeah, domain instead of IP may be a thing. It worked in prev. version so it's probably some kind of bug.
I'm not sure if I'll have time to fix it. I'm currently thinking about re-writing whole ext. from scratch and I only focus on resolving some urgent issues here. Again, I'm using this ext. at work and yes, sometimes it just crushes but most of times it works; so currently I'm just trying to help people have at least same experience I have.

**Comment by addcms** [comment] 2015-12-07 20:47
Yeah sometimes it just stops working and I have to restart brackets. But this is still the best FTP brackets ext out there.

**Comment by Equals182** [comment] 2015-12-07 20:50
Oh, I wish it would work perfectly. I'll do my best to make next version better.

**Comment by Equals182** [comment] 2017-01-10 23:17
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊

**Closed by Equals182** 2017-01-10 23:17 UTC
